// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fshoqpmxuinzlvfgnppe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzaG9xcG14dWluemx2ZmducHBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzIxODQsImV4cCI6MjA2MDQwODE4NH0.JvTBZnYU6leF-fpYoPRMfPV5JAC9Ut6tozOWIsVXKrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);